/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
    theme: {
        extend: {
            fontSize: {
                xs: ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "400" }],
                sm: ["0.875rem", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "400" }],
                base: ["1rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "400" }],
                lg: ["1.125rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
                xl: ["1.25rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "600" }],
                "2xl": ["1.5rem", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "700" }],
                "3xl": ["1.875rem", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "700" }],
                "4xl": ["2.25rem", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "800" }],
                "5xl": ["3rem", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "800" }],
                "6xl": ["3.75rem", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "900" }],
                "7xl": ["4.5rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "900" }],
                "8xl": ["6rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "900" }],
                "9xl": ["8rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "900" }],
            },
            fontFamily: {
                heading: ["prompt", "sans-serif"],
                paragraph: ["sarabun", "sans-serif"]
            },
            colors: {
                primary: "#0a0a0a",
                "primary-foreground": "#00ff88",
                secondary: "#00ff88",
                "secondary-foreground": "#0a0a0a",
                background: "#0f0f0f",
                foreground: "#ffffff",
                card: "#1a1a1a",
                "card-foreground": "#ffffff",
                popover: "#1a1a1a",
                "popover-foreground": "#ffffff",
                muted: "#262626",
                "muted-foreground": "#a3a3a3",
                accent: "#ff0080",
                "accent-foreground": "#ffffff",
                destructive: "#ff4444",
                "destructive-foreground": "#ffffff",
                border: "#333333",
                input: "#262626",
                ring: "#00ff88",
                // Gaming theme colors
                "neon-green": "#00ff88",
                "neon-pink": "#ff0080",
                "neon-blue": "#00aaff",
                "neon-purple": "#aa00ff",
                "cyber-dark": "#0a0a0a",
                "cyber-gray": "#1a1a1a",
                "cyber-light": "#262626",
                "game-accent": "#ffff00",
                gridline: "#333333",
                "text-primary": "#ffffff",
                "text-secondary": "#00ff88",
                lavendergradientstart: "#ff0080",
                lavendergradientend: "#00aaff",
                "dark-background": "#0f0f0f",
                buttonbackground: "#00ff88",
                buttonforeground: "#0a0a0a"
            },
        },
    },
    future: {
        hoverOnlyWhenSupported: true,
    },
    plugins: [require('@tailwindcss/container-queries'), require('@tailwindcss/typography')],
}
